default_language_version:
  python: python3.12
default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml", "src", "tests"]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.2.2
    hooks:
      - id: pylint
        args: ["--rcfile=pyproject.toml", "src", "tests"]
