default_language_version:
  python: python3.12
default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: ["--fix"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --config-file=pyproject.toml
        language: system
        types: [python]
        require_serial: true

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint --rcfile=pyproject.toml src
        language: system
        types: [python]
        files: ^src/
        exclude: ^tests/
        require_serial: true
